# Generated by Django 5.1.15 on 2026-10-03 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="google_play", max_length=16)),
                ("plan", models.CharField(max_length=16)),
                ("product_id", models.CharField(max_length=100)),
                ("purchase_token", models.CharField(max_length=512, unique=True)),
                ("linked_purchase_token", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_grace", "In grace period"),
                            ("on_hold", "On hold"),
                            ("paused", "Paused"),
                            ("canceled", "Canceled (active until expiry)"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renewing", models.BooleanField(default=False)),
                ("acknowledged", models.BooleanField(default=False)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "last_verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
