# Generated by Django 5.1.15 on 2026-10-03 12:55

import apps.core.ids
import apps.reports.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        default=apps.core.ids.generate_report_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        default=apps.core.ids.generate_share_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_evidence", "Waiting for photos to upload"),
                            ("final", "Final"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending_evidence",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("snapshot", models.JSONField(default=dict)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=apps.reports.models.report_pdf_upload_to,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_name", models.CharField(blank=True, max_length=150)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="jobs.job",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("issue", "Issue / dispute"), ("comment", "Comment")],
                        default="issue",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField(max_length=2000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
